### ISSUE TITLE
Backspace triggers System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by Ag0s** [0xbadjuju/Tokenvator#1]
While backspacing a command you can go back beyond the normal prompt resulting in:

`System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimentsion.
Parameter name: left
Actual value was -1.
  at System.ConsoleSetCursorPosition(Int32 left, Int32 top)
  at Tokenvator.TabComplete.KeyInput(StringBuilder stringBuilder, ConsoleKeyInfo at keyDown)
  at Tokenvator.TabComplete.ReadLine()
  at Tokenvator.MainLoop.Run()`

Pressing return will return you to normal state.

**Comment by 0xbadjuju** [comment]
Just pushed a potential fix to the dev branch and uploaded a release containing the fix

https://github.com/0xbadjuju/Tokenvator/releases/tag/v1.3.1

**Comment by Ag0s** [comment]
Will check it soon. I'll get back to you once I have. Thanks for picking this up so quickly.

**Comment by 0xbadjuju** [comment]
This should be fixed in Release 2, closing this issue.
