### ISSUE TITLE
sgKey.snk file missing

### ISSUE THREAD

**Issue by ghost** [0xbadjuju/Tokenvator#4]
well met this problem when establishing the project, and i ve found an issue dealing with it but it had been closed, so somebody do me a favor please?

**Comment by 0xbadjuju** [comment]
The sgKey.snk file is intended for use in strong name signing the assembly. Strong naming the executable doesn't seem to offer enough value given the headaches it causes, so I'm removing the dependency for it from the project file in the dev branch. 

Commit: [https://github.com/0xbadjuju/Tokenvator/commit/a0e237df5ffd257c3bc5cd8f4d0bdc21b7b6eb26](https://github.com/0xbadjuju/Tokenvator/commit/a0e237df5ffd257c3bc5cd8f4d0bdc21b7b6eb26)

If you still would like to generate the sgKey.snk file, it can be done with the command: 
`C:\Program Files\Microsoft SDKs\Windows\v7.0\Bin\x64\sn.exe -k sgKey.snk `

**Comment by ghost** [comment]
So it means i could remove the SNK file link from the project directly just by myself ? Thanks for helping .
