### ISSUE TITLE
BypassUAC fails on windows 10 1703

### ISSUE THREAD

**Issue by DavidXanatos** [0xbadjuju/Tokenvator#8]
BypassUAC fails on windows 10 1703

commenting out
//Console.WriteLine(" [+] Initialized SID: {0}", pSID.ToInt32());
in SetTokenInformation seams to solve the issue, strange

EDIT: change it to ToInt64 and it works
there is also a crash in Tockens:dispose but probably unrelated

**Comment by 0xbadjuju** [comment]
Hey DavidXanatos, thanks for pointing this out. I'll take a look at it at both issues and push a fix this week.

**Comment by 0xbadjuju** [comment]
This issue is fixed in my lab - I've pushed the fix to master and updated the release.
