### ISSUE TITLE
Retarget to Framework 3.5

### ISSUE THREAD

**Issue by CaledoniaProject** [0xbadjuju/Tokenvator#9]
The master branch currently targets Framework 4.5, which is not "Import the project into Visual Studio. The current target framework is .Net 3.5. "

Can you change that?

**Comment by 0xbadjuju** [comment]
I've migrated and updated the instruction for building Tokenvator to the [wiki](https://github.com/0xbadjuju/Tokenvator/wiki), and added a msbuild.exe [script](https://github.com/0xbadjuju/Tokenvator/blob/master/MSBuild.xml) to build for both .Net 3.5 and .Net 4.5. 

Updated instructions for building for .Net 3.5 and .Net 4.5 targets can be found here: https://github.com/0xbadjuju/Tokenvator/wiki/Building-Tokenvator

**Comment by CaledoniaProject** [comment]
Thanks!
